Dev #497
dsgoficial/DsgTools pull request #547
Opened 2021-03-22 19:21 UTC by franciscocamellon

a finished algorithm, able to be merged.

2021-03-25 17:21 UTC, jpesperidiao reviewed
Verifiquei uma parte do código. A maioria é a respeito de docstring, mas tem alguns pontos sobre o código em si.

Qual foi a modificação no base "banco_capacitacao.sqlite"?

2021-03-29 12:07 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +        """Gets the current color name from mColorButton."""
Feito

2021-03-29 12:11 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +        return self.mColorButton.colorChanged.connect(self.updateColor)
Feito

2021-03-29 12:12 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +        """Sets the color in the mColorButton and in the lineEdit."""
Feito

2021-03-29 12:17 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +from qgis.gui import QgsMapLayerComboBox, QgsFieldComboBox
Feito

2021-03-29 12:17 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +class LayerAndFieldSelectorWidget(QtWidgets.QWidget, FORM_CLASS):
Feito

2021-03-29 12:43 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +class ColorSelectorWidget(QtWidgets.QWidget, FORM_CLASS):
Feito

2021-03-29 12:59 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        self.mMapLayerComboBox.layerChanged.connect(lambda: self.setLayer())
Feito

2021-03-29 13:11 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        """Retrieves a loaded layers list."""
Feito

2021-03-29 13:12 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        """Gets the current layer from a QgsMapLayerComboBox."""
Feito

2021-03-29 13:12 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +    def getCurrentField(self):
Feito

2021-03-29 13:23 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        :param (dict) rules: dictionary with conditional rules;
Feito

2021-03-29 15:30 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        return lyr, fld
Feito

2021-03-29 15:35 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        """
Feito

2021-03-29 15:35 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        """
Feito

2021-03-29 15:41 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        """Sets a field to be used with OTW."""
Feito

2021-03-31 12:18 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        self.lyr_list = [layer.name()
Feito

2021-05-03 12:43 UTC, jpesperidiao commented on tests/test_ValidationAlgorithms.py
> +                    '__comment' : "Tests 2",
Existe arquivos de teste para 3 testes. Não vai utilizar o 3º?

Faltou testar somente com feições selecionadas.

2021-05-03 12:44 UTC, jpesperidiao requested changes
Tem uns comentários indicando a necessidade de modificações. Caso tenha dúvidas, só me dar um toque.

2021-05-10 12:35 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +    def widgetSizeHint(self):
Feito

2021-05-10 12:39 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +from qgis.PyQt import QtCore, QtWidgets, uic
Feito

2021-05-10 12:40 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +from qgis.PyQt.QtWidgets import QWidget, QLineEdit, QHBoxLayout, QVBoxLayout
Feito

2021-05-10 12:45 UTC, franciscocamellon commented on gui/CustomWidgets/ValidationWidgets/validationSetOfAttributesWidget.ui
> +<?xml version="1.0" encoding="UTF-8"?>
Feito

2021-05-10 14:28 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/colorSelectorWidget.py
> +    mColorButton = QgsColorButton()
Feito

2021-05-10 14:30 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +    mMapLayerComboBox = QgsMapLayerComboBox()
Feito

2021-05-10 14:34 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        self.project = QgsProject.instance()
Feito

2021-05-10 16:18 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        self.getLoadedLayers()
Feito

2021-05-10 16:25 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        Sets a layer to be used with OTW.
Feito

2021-05-10 17:15 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        Sets the currently selected field to be used with OTW.
Feito

2021-05-10 18:24 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +    def getCurrentLayerNField(self):
Feito

2021-05-10 18:24 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        layer to be used with OTW.
Feito

2021-05-10 18:25 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +    def widgetSizeHint(self):
Feito

2021-05-10 18:25 UTC, franciscocamellon commented on gui/CustomWidgets/BasicInterfaceWidgets/layerAndFieldSelectorWidget.py
> +        the OTW's resize policies.
Feito

2021-05-11 13:34 UTC, jpesperidiao commented on gui/CustomWidgets/OrderedPropertyWidgets/orderedTableWidget.py
> +        self.dataLoaded.emit(stateDict)
Ignorar. Sinais executam na mesma _thread_ em que foram emitidos.

2021-05-12 16:23 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        :param (QgsVectorLayer) layerList: list from all loaded layers.
Feito

2021-05-12 16:24 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                self.tr('Point Flags')
Feito

2021-05-12 16:24 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                self.tr('Linestring Flags')
Feito

2021-05-12 16:25 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                self.tr('Polygon Flags')
Feito

2021-05-12 16:57 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +    def checkedFeatures(self, stateDict, onlySelected):
Feito

2021-05-12 17:20 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        lyr = QgsProject.instance()
Feito

2021-05-12 17:58 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        for key, value in stateDict.items():
Feito

2021-05-12 17:59 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                parameters = {
Feito

2021-05-12 17:59 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        :return: (tuple-of-QgsVectorLayer) filled flag layers.
Feito

2021-05-12 18:05 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                self.addRuleToLayer(lyr.mapLayersByName(
Feito

2021-05-12 18:06 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +    def addRuleToLayer(self, lyr, values):
Feito

2021-05-12 18:08 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +            if field.name() == values['layerField'][1]:
Feito

2021-05-12 18:13 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        :param onlySelected: (boolean) true or false;
Feito

2021-05-12 18:18 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        :param featureDict: (dict) a dictionary with a list QgsFeatures
Feito

2021-05-12 18:18 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        for keys, values in rules.items():
Feito

2021-05-12 18:25 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +            flagText = '{name}'.format(name=values["description"])
Feito

2021-05-12 18:26 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        self.font.setBold(True)
Feito

2021-05-12 18:29 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +        for k, values in rules.items():
Feito

2021-05-12 18:34 UTC, franciscocamellon commented on core/DSGToolsProcessingAlgs/Algs/ValidationAlgs/enforceAttributeRulesAlgorithm.py
> +                    values['layerField'][1],
Neste caso a lista sempre terá o índice 1 devido a lista ser [camada, atributos da camada]

2021-05-19 13:52 UTC, franciscocamellon commented on gui/ProcessingUI/enforceAttributeRulesWrapper.py
> +    Docstring
Feito

2021-07-19 19:11 UTC, franciscocamellon commented on gui/CustomWidgets/OrderedPropertyWidgets/orderedTableWidget.py
> +        self.dataLoaded.emit(stateDict)
Ok

2021-07-19 19:15 UTC, franciscocamellon reviewed
Revisões feitas

2021-07-19 19:42 UTC, merged